[build]
  publish = "."

[[headers]]
  for = "/cricket_pro.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment; filename=cricket_pro.apk"
